project:
  type: book
  output-dir: docs

book:
  title: "Introduction to R"
  subtitle: "Quantitative Methods I"
  author: "Malo Jan"
  date: last-modified
  repo-url: https://github.com/malojan/2024_intro_r
  site-url: https://malojan.github.io/2024_intro_r/
  repo-actions: [edit]
  search: true
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - setup.qmd
    - part: "Getting started with R and Rstudio"
      chapters:
        - session01/workflow.qmd
        - session01/basics.qmd
        - session01/help.qmd
    - part: "Manipulating and describing data"
      chapters:
        - session02/0201_manipulate.qmd
        - session02/0202_reshape.qmd
    - part: "Visualizing data"
      chapters:
        - session03/03_dataviz.qmd
    - part: "Testing relationships"
      chapters:
        - session04/04_relationships.qmd
    - part: "Regression analysis"
      chapters:
        - session05/correlation_regression.qmd
    - part: "Multivariate analysis"
      chapters:
        - session06/06_modelling.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-block-background: true
    code-block-border-left: "#31BAE9"
    highlight-style: pygments
    toc: true
    toc-location: right
    code-copy: true
    code-link: true
    citations-hover: true
    footnotes-hover: true
    embed-resources: false
    grid: 
      sidebar-width: 300px
      margin-width: 300px
  pdf:
    documentclass: scrreprt

editor: source