---
title: "Introduction to R"
author: "Malo Jan"
incremental: false
format: revealjs
self-contained: true
---

## The goals of this class {.smaller}

- Lab sessions of the quantitative methods class taught by J. Rovny
- Gain practical experience applying quantitative methods using programming
- We will learn to import, manipulate, clean, visualize data, compute descriptive statistics and run statistical models
- Programming : instructing computers to perform specific tasks by writing code using programming languages (such as Python, Java, C++ or...R)
- R : free, open-source, widely used in social sciences, reproducible
- Teach you the basics, give you the willigness to learn more by yourself and prepare for Quant 2 and use of quantitative methods in your future research

## About Your Instructor {.smaller}

-   Malo Jan, PhD candidate in Political Science at CEE Sciences Po
-   Graduated from the master's program two years ago
-   Research focus: Political Parties, Political Behavior, and Climate Politics
    -   And... I'm quite passionate about data science and all of the (fun and unexpected) things we can do with R nowadays

## Prerequisites {.smaller}

-   This class is designed for complete beginners in R and require no programming knowledge but willingness to learn and practice
- Different backgrounds :
  - Begginers : please ask questions if I am moving too quickly
  - Advanced students : feel free to request additional resources to go further 

## Course material {.smaller}

-   Material of each session provided beforehand as a **zip file**
-   [A website](https://malojan.github.io/introduction-r/)
-   A Moodle page to upload the exercises.

## Course validation {.smaller}

| Assignments | Description | Due date                | Weight |
|-------------|-------------|-------------------------|--------|
| Exercise 1  | Individual  | 7 days after Session 1  | 5%     |
| Exercise 2  | Individual  | 7 days after Session 2  | 5%     |
| Exercise 3  | Individual  | 7 days after Session 3  | 5%     |
| Exercise 4  | Individual  | 7 days after Session 4  | 5%     |
| Exercise 5  | Group       | 14 days after session 6 | 10%    |

# 

Let's turn to RStudio to practice!
