<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.41">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Introduction to R – 8&nbsp; Exploring correlations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../session06/06_modelling.html" rel="next">
<link href="../session04/04_relationships.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../session05/correlation_regression.html">Regression analysis</a></li><li class="breadcrumb-item"><a href="../session05/correlation_regression.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exploring correlations</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malojan/introduction-r" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Setting up R and Rstudio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting started with R and Rstudio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session01/workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Rstudio, scripts, quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session01/basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session01/help.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Getting help and dealing with errors</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Manipulating and describing data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session02/0201_manipulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Manipulating data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session02/0202_reshape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reshaping data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Visualizing data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session03/03_dataviz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data visualization</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Testing relationships</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session04/04_relationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Testing relationships</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session05/correlation_regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exploring correlations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Multivariate analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session06/06_modelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Multivariate Relationships</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#running-a-regression-in-r" id="toc-running-a-regression-in-r" class="nav-link active" data-scroll-target="#running-a-regression-in-r"><span class="header-section-number">8.1</span> Running a regression in R</a></li>
  <li><a href="#extracting-regression-results" id="toc-extracting-regression-results" class="nav-link" data-scroll-target="#extracting-regression-results"><span class="header-section-number">8.2</span> Extracting regression results</a></li>
  <li><a href="#regression-with-categorical-independent-variables" id="toc-regression-with-categorical-independent-variables" class="nav-link" data-scroll-target="#regression-with-categorical-independent-variables"><span class="header-section-number">9</span> Regression with categorical independent variables</a></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn"><span class="header-section-number">10</span> Your turn !</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/malojan/introduction-r/edit/main/session05/correlation_regression.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../session05/correlation_regression.html">Regression analysis</a></li><li class="breadcrumb-item"><a href="../session05/correlation_regression.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exploring correlations</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exploring correlations</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>After examining the relationship between two categorical variables (using the chi-square test) and between a categorical and a continuous variable (using the t-test), we will now explore the relationship between two continuous variables using correlation and simple regression.</p>
<p>To explore this, we will examine data on economic voting. Economic voting is a theory suggesting that voters reward or punish the incumbent government based on the state of the economy, and we aim to test this theory to see if it holds.</p>
<p>Our research question is: Is there a relationship between the state of the economy and the performance of the incumbent party in the United States? To investigate this, I am using an example developed by François Briatte, the previous instructor of this course, which uses data from Larry Bartels on economic voting in the United States.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># If you haven't already, install the following packages with install.packages("package_name")</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span> <span class="co"># Because we always need it</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span> <span class="co"># To work with regression results</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">stargazer</span><span class="op">)</span> <span class="co"># To print regression results nicely</span></span>
<span></span>
<span></span>
<span><span class="co"># Import dataset</span></span>
<span></span>
<span><span class="va">us_elections</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/us_elections.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">us_elections</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 10
    year incumbent_margin income_growth incumbent  candidate_winner
   &lt;dbl&gt;            &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           
 1  1948             4.48          4.67 Truman     Truman          
 2  1952           -10.8           2.42 Stevenson  Eisenhower      
 3  1956            15.4           0.54 Eisenhower Eisenhower      
 4  1960            -0.17         -0.15 Nixon      Kennedy         
 5  1964            22.6           3.35 Johnson    Johnson         
 6  1968            -0.7           1.36 Humphrey   Nixon           
 7  1972            23.2           2.49 Nixon      Nixon           
 8  1976            -2.06          1.26 Ford       Carter          
 9  1980            -9.74         -0.96 Carter     Reagan          
10  1984            18.2           2.85 Reagan     Reagan          
11  1988             7.72          1.24 Bush Sr    Bush Sr         
12  1992            -5.56          0.57 Bush Sr    Clinton B       
13  1996             8.51          1.32 Clinton B  Clinton B       
14  2000             0.51          1.57 Gore       Bush Jr         
15  2004             2.46          1.19 Bush Jr    Bush Jr         
16  2008            -7.27         -0.79 McCain     Obama           
17  2012             3.84          0.32 Obama      Obama           
# ℹ 5 more variables: candidate_loser &lt;chr&gt;, party_incumbent &lt;chr&gt;,
#   winner_incumbent &lt;lgl&gt;, party_winning &lt;chr&gt;, tenure &lt;dbl&gt;</code></pre>
</div>
</div>
<p>In this dataset, we have only 17 observations on each election in the US from 1948 to 2012. To operationalize these two concepts, state of the economy and performance of the incumbent party, we rely on two variables available in this dataset : the incumbent party’s margin of victory and the growth of disposable income per capita in the two last quarters before the election. The incumbent party’s margin of victory is the difference between the incumbent party’s vote share and the vote share of the main opposition party. Real disposable income here is a measure of people’s purchasing power after accounting for taxes and inflation.</p>
<p>A first way to look at the relationship between those two variables is to compute the correlation between them. To look at correlations we use the cor() function that takes two continuous variables as argument. Note that in the case we have missing values in our data, the <code>cor</code> function will not work. In that case, you can add <code>use = "complete.obs"</code> as argument in the <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code>function.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">us_elections</span><span class="op">$</span><span class="va">incumbent_margin</span>, <span class="va">us_elections</span><span class="op">$</span><span class="va">income_growth</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5072114</code></pre>
</div>
</div>
<p>The result is a correlation coefficient of 0.5. A correlation coefficient measures the strength and direction of a linear relationship between two variables. The correlation coefficient ranges between -1 and 1, where -1 indicates a perfect negative linear relationship, 1 indicates a perfect positive linear relationship, and 0 indicates no linear relationship. Correlations coefficients give you a indicator of the intensity of the relationships between two continuous variables. Here we seen that the coefficient is ~ 0.5, which indicates a moderate positive relationship between the two variables. As the state of the economy grows, the incumbent party’s margin of victory increases.</p>
<p>We can also test whether this correlation is statistically significant. To do so, we can use the <code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code> function, working in the same way as the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function. Here, we are testing the null hypothesis that the correlation between the two variables is equal to 0 and the p-value is the probability of observing a correlation at least as strong if the null hypothesis were true. The p-value here is 0.038, which is below the conventional threshold of 0.05, so we can reject the null hypothesis and conclude that the correlation is statistically significant.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">us_elections</span><span class="op">$</span><span class="va">incumbent_margin</span>, <span class="va">us_elections</span><span class="op">$</span><span class="va">income_growth</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  us_elections$incumbent_margin and us_elections$income_growth
t = 2.2794, df = 15, p-value = 0.0377
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.03513119 0.79423161
sample estimates:
      cor 
0.5072114 </code></pre>
</div>
</div>
<p>But still here, we are not able to say how much the incumbent party’s margin of victory increases when the state of the economy grows. This is where correlation often falls short and linear regression comes in. Linear regression is a statistical method that models the relationship between a dependent variable and one or more independent variables. In our case, we want to model the relationship between the incumbent party’s margin of victory and the growth of disposable income per capita. Linear regression is considered a workhorse in quantitative social sciences. It’s safe to say that publishing quantitative results can be challenging without using this or a more sophisticated model. Whether you’re a quantitative researcher aiming to employ it or a qualitative researcher seeking to comprehend a quantitative article relevant to your work, understanding how regression operates is crucial.</p>
<p>When dealing with a single independent variable, we refer to it as simple linear regression, which is our primary focus today. In the next session, we will delve into multiple linear regression, involving more than one independent variable.</p>
<p>In linear regression, our objective is to establish a linear relationship between one or more independent variables and a <em>continuous</em> dependent variable. However, when working with a dependent variable that is not continuous, other models become relevant, and these will be explored in the upcoming semester. One such model is logistic regression, which is employed when the dependent variable is binary (e.g., whether individuals have voted for Trump or not).</p>
<p>Our regression equation for each incumbent party is a given year <span class="math inline">\({i}\)</span> is written below.</p>
<p><span class="math display">\[
margin_{i} = \beta_{0} + \beta_{1}income_{i} + \epsilon_{i}
\]</span> The goal of the regression is to estimate the parameters of our model, which are <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span>. The error term <span class="math inline">\(\epsilon_{i}\)</span> is not a parameter: once the model is estimated, the residuals give us an estimate of it.</p>
<ul>
<li>
<span class="math inline">\(\beta_{0}\)</span> corresponds to the intercept of the regression line. It provides the estimated value of the margin of victory for the incumbent party when the growth of real disposable income is 0. This intercept may or may not have a meaningful interpretation depending on the context of your data.</li>
<li>
<span class="math inline">\(\beta_{1}\)</span> represents the slope of the regression line. It indicates the estimated change in the margin of victory for the incumbent party for a one-unit change in the growth of real disposable income. This coefficient is of particular interest as it shows the direction and the size of the relationship between the two variables, in the units of these variables.</li>
<li>
<span class="math inline">\(\epsilon_{i}\)</span> is the error term that accounts for the difference between the observed and predicted values of the dependent variable. It captures the variability in the dependent variable that is not explained by the independent variable(s).</li>
</ul>
<p>To estimate the parameters of our model, we use the method of ordinary least squares (OLS). It allows to fit a line through the data points in a way that minimizes the sum of the squared prediction errors. In other words, it minimizes the distance between the line and the data points. This is why it is called “least squares”. This might still sound abstract to you so let’s look at the data !</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">elec_plot</span> <span class="op">&lt;-</span> <span class="va">us_elections</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">income_growth</span>, <span class="va">incumbent_margin</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Create a scatter plot</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Add a line at 0 on the y-axis</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, lty <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Add president names</span></span>
<span>  <span class="fu">ggrepel</span><span class="fu">::</span><span class="fu"><a href="https://ggrepel.slowkow.com/reference/geom_text_repel.html">geom_text_repel</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_c.html">str_c</a></span><span class="op">(</span><span class="va">incumbent</span>, <span class="st">"-"</span>, <span class="va">year</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Change axix labels</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Incumbent party popular vote margin (%)"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"Q14/Q15 growth in real disposable income per capita (%)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">elec_plot</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="correlation_regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The goal of linear regression is to find the best-fitting straight line that represents the relationship between two variables based on the given data points. The “best fit” line is determined by minimizing the distance between the line and the actual data points. This distance is measured using residuals, which are the vertical distances from each data point to the line. The line that results in the smallest sum of squared residuals provides the best approximation of the relationship between the variables. For example, if we examine the plot below, we can observe that the red and blue lines do not fit the data points well, whereas the black line represents a better fit.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">elec_plot</span>  <span class="op">+</span></span>
<span>  <span class="co"># One first "wrong" regression line</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span></span>
<span>    intercept <span class="op">=</span> <span class="op">-</span><span class="fl">6</span>,</span>
<span>    slope <span class="op">=</span> <span class="fl">10</span>,</span>
<span>    color <span class="op">=</span> <span class="st">"blue"</span>,</span>
<span>    linetype <span class="op">=</span> <span class="st">"dashed"</span>,</span>
<span>    size <span class="op">=</span> <span class="fl">1</span>,</span>
<span>    alpha <span class="op">=</span> <span class="fl">0.4</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># A second "wrong" regression line</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span></span>
<span>    intercept <span class="op">=</span> <span class="fl">0</span>,</span>
<span>    slope <span class="op">=</span> <span class="fl">1.5</span>,</span>
<span>    color <span class="op">=</span> <span class="st">"red"</span>,</span>
<span>    linetype <span class="op">=</span> <span class="st">"dashed"</span>,</span>
<span>    size <span class="op">=</span> <span class="fl">1</span>,</span>
<span>    alpha <span class="op">=</span> <span class="fl">0.4</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># The true regression line</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span></span>
<span>    method <span class="op">=</span> <span class="st">"lm"</span>,</span>
<span>    linetype <span class="op">=</span> <span class="st">"dashed"</span>,</span>
<span>    color <span class="op">=</span> <span class="st">"black"</span>,</span>
<span>    se <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>    size <span class="op">=</span> <span class="fl">1</span>,</span>
<span>    alpha <span class="op">=</span> <span class="fl">0.4</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="correlation_regression_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Linear regression not only provides us with the best-fitting line but also offers valuable information about the uncertainty associated with the estimated model parameters. This uncertainty can be represented by a confidence interval around the regression line. Below, you can see this with the grey area around our regression line: for each value of income growth, it shows the range of plausible values for the average predicted margin. The wider the grey area, the more uncertain our predictions are.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">elec_plot</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span>, color <span class="op">=</span> <span class="st">"black"</span>, se <span class="op">=</span> <span class="cn">TRUE</span>, size <span class="op">=</span> <span class="fl">1</span>, alpha <span class="op">=</span> <span class="fl">0.4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="correlation_regression_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="running-a-regression-in-r" class="level2" data-number="8.1"><h2 data-number="8.1" class="anchored" data-anchor-id="running-a-regression-in-r">
<span class="header-section-number">8.1</span> Running a regression in R</h2>
<p>Now we have a better idea of what a regression is, let’s run our first model. In R it is really easy to do ! You need to use the <code><a href="https://rdrr.io/r/stats/lm.html">stats::lm()</a></code> function. You need to insert a formula with on the left, the variable you want to explain and the right, the independent variables and in between, a <code>~</code>. Before running the model, we have to make sure to know whether we have missing values or not in our data because the model will just drop them out and it is better to be aware of this.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">incumbent_margin</span> <span class="op">~</span> <span class="va">income_growth</span>, data <span class="op">=</span> <span class="va">us_elections</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once we have run the model, we have to interpret the results. In R, you have different ways to look at and to manipulate the results of a regression model. To have a quick look at the results, you can use the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function. It provides you with the main results of the model.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = incumbent_margin ~ income_growth, data = us_elections)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.860  -5.343  -1.036   4.537  14.883 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)    -0.8726     3.1754  -0.275   0.7872  
income_growth   3.6707     1.6104   2.279   0.0377 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.431 on 15 degrees of freedom
Multiple R-squared:  0.2573,    Adjusted R-squared:  0.2077 
F-statistic: 5.196 on 1 and 15 DF,  p-value: 0.0377</code></pre>
</div>
</div>
<ul>
<li><p>Our estimate for the intercept - 0.873. This means that if the Q14/Q15 growth in real disposable income per capita is 0, the predicted incumbent party popular vote margin is -0.873. However, this estimate is very uncertain (standard error of 3.18, p-value of 0.79): it is not statistically different from 0, so we cannot conclude that the incumbent party loses the election on average when there is no economic growth.</p></li>
<li><p>Our estimate for for our first coefficient is 3.67. This is the slope of the regression line. That means that for each percentage point increase in growth in real disposable income per capita, the incumbent party popular vote margin increases by 3.67 percentage points.</p></li>
<li><p>Std. error is the standard error of the coefficient. It is a measure of the uncertainty of the estimate. The smaller the standard error, the more precise the estimate.</p></li>
<li><p>t value is the t statistic. It is computed by dividing the coefficient by its standard error (<code>3.67/1.61 = 2.28</code>). It measures how many standard errors the coefficient is away from 0. With large samples, a coefficient is statistically significant at the 5% level when the absolute t value is above 1.96. With only 15 degrees of freedom, as here, the threshold is higher: about 2.13 (<code>qt(0.975, 15)</code>).</p></li>
<li><p>p.value :<code>2 * (1 - pt(abs(2.28), 15))</code>, df being the degree of freddom which our number of observations - our number of coefficients (17-2)</p></li>
<li><p>Looking at the p-value, we see that the p-value of our main esimate is inferior to 0.05, showing that it is statistically significant at the 5% level.</p></li>
<li><p>When we run a regression, we also care about how good is our model to explain the variation of our outcome variable. The <span class="math inline">\(R^{2}\)</span> is the share of the variance of our dependent variable that our model is able to explain. It goes from 0 to 1. If the <span class="math inline">\(R^{2}\)</span> = 1, our model entirely explains Y (that will never happens). In social sciences we are happy with <span class="math inline">\(R^{2}\)</span> of 0.2…</p></li>
</ul></section><section id="extracting-regression-results" class="level2" data-number="8.2"><h2 data-number="8.2" class="anchored" data-anchor-id="extracting-regression-results">
<span class="header-section-number">8.2</span> Extracting regression results</h2>
<p>While just looking at the summary of the model is a good way to get a first idea of the results, you can also extract the results in a more detailed way with the <code>broom</code> package that has super handy functions to get the results of the regression model in tidy format. The <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> function allows you to extract the coefficient of the models and to get their confidence intervals and p values as a dataframe. This can be used to create coefficient plots, which is a good way to visualize the results of the regression model, especially when you have multiple variables. If the confidence interval bar crosses the dashed 0 line, it indicates that our coefficient will not be statistically significant. Remember that the sizes of coefficients are not directly comparable because they are not calculated on the same scale. The magnitude of each coefficient depends on the units of the corresponding independent variable. Therefore, comparing coefficients without considering their scales could lead to misleading interpretations.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = incumbent_margin ~ income_growth, data = us_elections)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.860  -5.343  -1.036   4.537  14.883 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)    -0.8726     3.1754  -0.275   0.7872  
income_growth   3.6707     1.6104   2.279   0.0377 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.431 on 15 degrees of freedom
Multiple R-squared:  0.2573,    Adjusted R-squared:  0.2077 
F-statistic: 5.196 on 1 and 15 DF,  p-value: 0.0377</code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_coeffs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">model</span>, conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">model_coeffs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term          estimate std.error statistic p.value conf.low conf.high
  &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)     -0.873      3.18    -0.275  0.787    -7.64       5.90
2 income_growth    3.67       1.61     2.28   0.0377    0.238      7.10</code></pre>
</div>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_coeffs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">term</span>, y <span class="op">=</span> <span class="va">estimate</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Create dot for our estimates with a bar for confidence intervals</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_pointrange</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">conf.low</span>, ymax <span class="op">=</span> <span class="va">conf.high</span><span class="op">)</span><span class="op">)</span>  <span class="op">+</span></span>
<span>  <span class="co"># Create a dashed line at 0</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Add labels coefficient number as label</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_text.html">geom_label</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>, vjust <span class="op">=</span> <span class="op">-</span><span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="co"># invert y/x axes</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="correlation_regression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To extract model fit statistics, you can use the <code><a href="https://generics.r-lib.org/reference/glance.html">glance()</a></code> function. This function provides you with the <span class="math inline">\(R^{2}\)</span>, the adjusted <span class="math inline">\(R^{2}\)</span>.</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.257         0.208  9.43      5.20  0.0377     1  -61.2  128.  131.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>One last useful function from the <code>broom</code> package is <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>. This will give you the predictions of our model (our fitted values) and our residuals (the errors). This is useful to calculate different diagnostics that we will see in a further session.</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">model</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 8
   incumbent_margin income_growth .fitted .resid   .hat .sigma  .cooksd
              &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
 1             4.48          4.67  16.3   -11.8  0.377    8.91 0.758   
 2           -10.8           2.42   8.01  -18.9  0.0911   8.21 0.221   
 3            15.4           0.54   1.11   14.3  0.0788   8.91 0.107   
 4            -0.17         -0.15  -1.42    1.25 0.126    9.76 0.00146 
 5            22.6           3.35  11.4    11.2  0.173    9.19 0.178   
 6            -0.7           1.36   4.12   -4.82 0.0588   9.67 0.00867 
 7            23.2           2.49   8.27   14.9  0.0956   8.82 0.145   
 8            -2.06          1.26   3.75   -5.81 0.0592   9.63 0.0127  
 9            -9.74         -0.96  -4.40   -5.34 0.217    9.63 0.0567  
10            18.2           2.85   9.59    8.62 0.123    9.45 0.0667  
11             7.72          1.24   3.68    4.04 0.0593   9.70 0.00615 
12            -5.56          0.57   1.22   -6.78 0.0774   9.58 0.0235  
13             8.51          1.32   3.97    4.54 0.0589   9.68 0.00769 
14             0.51          1.57   4.89   -4.38 0.0600   9.69 0.00733 
15             2.46          1.19   3.50   -1.04 0.0597   9.76 0.000407
16            -7.27         -0.79  -3.77   -3.50 0.195    9.71 0.0206  
17             3.84          0.32   0.302   3.54 0.0908   9.71 0.00773 
# ℹ 1 more variable: .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
<p><code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code> is also useful to combine your regression results with your initial dataframe and do some graphs of your results.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">model</span>, <span class="va">us_elections</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">income_growth</span>, y <span class="op">=</span> <span class="va">incumbent_margin</span>, label <span class="op">=</span> <span class="va">incumbent</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>colour <span class="op">=</span> <span class="st">"black"</span>, alpha <span class="op">=</span> <span class="fl">.25</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>,</span>
<span>              color <span class="op">=</span> <span class="st">"black"</span>,</span>
<span>              linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span>  <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_segment.html">geom_segment</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>xend <span class="op">=</span> <span class="va">income_growth</span>, yend <span class="op">=</span> <span class="va">.fitted</span><span class="op">)</span>,</span>
<span>               alpha <span class="op">=</span> <span class="fl">0.5</span>,</span>
<span>               color <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ggrepel</span><span class="fu">::</span><span class="fu"><a href="https://ggrepel.slowkow.com/reference/geom_text_repel.html">geom_text_repel</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="correlation_regression_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The blue segments on the plot are the so-called residuals. These are the vertical distance between the ‘true’ value of our data to their fitted values on the regression line. The model is fitted by minimizing the sum of the squares of these distances. With this visualization, we can also say something about how our model is doing to predict certain points. For instance, our model is doing a bad job at predicting the results of the elections won by Eisenhower in 1952 and 1956.</p>
</section><section id="regression-with-categorical-independent-variables" class="level1" data-number="9"><h1 data-number="9">
<span class="header-section-number">9</span> Regression with categorical independent variables</h1>
<p>We have seen that we can use continuous variables in our regression. But we can also use categorical variables. For instance, we can use the <code>party_incumbent</code> variable to see whether the margin of the incumbent party differs depending on whether it is the Democratic or the Republican Party. Categorical variables have to be interepreted differently than continuous variables. The coefficient of a categorical variable is the difference between the mean of the outcome variable for the group of interest and the mean of the outcome variable for the reference group. Here, the reference group is Democrat. The coefficient of the party variable is the difference between the mean of the outcome variable for Republican and the mean of the outcome variable for Democrat. Here, our coefficient is 3.436, meaning that when the incumbent party is the Republican Party, its margin is on average 3.436 percentage points higher than when it is the Democratic Party. However, this difference is not statistically significant (p-value of 0.52). Consequently, we cannot conclude that Republican incumbents have higher margins than Democratic ones.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">us_elections</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 10
    year incumbent_margin income_growth incumbent  candidate_winner
   &lt;dbl&gt;            &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           
 1  1948             4.48          4.67 Truman     Truman          
 2  1952           -10.8           2.42 Stevenson  Eisenhower      
 3  1956            15.4           0.54 Eisenhower Eisenhower      
 4  1960            -0.17         -0.15 Nixon      Kennedy         
 5  1964            22.6           3.35 Johnson    Johnson         
 6  1968            -0.7           1.36 Humphrey   Nixon           
 7  1972            23.2           2.49 Nixon      Nixon           
 8  1976            -2.06          1.26 Ford       Carter          
 9  1980            -9.74         -0.96 Carter     Reagan          
10  1984            18.2           2.85 Reagan     Reagan          
11  1988             7.72          1.24 Bush Sr    Bush Sr         
12  1992            -5.56          0.57 Bush Sr    Clinton B       
13  1996             8.51          1.32 Clinton B  Clinton B       
14  2000             0.51          1.57 Gore       Bush Jr         
15  2004             2.46          1.19 Bush Jr    Bush Jr         
16  2008            -7.27         -0.79 McCain     Obama           
17  2012             3.84          0.32 Obama      Obama           
# ℹ 5 more variables: candidate_loser &lt;chr&gt;, party_incumbent &lt;chr&gt;,
#   winner_incumbent &lt;lgl&gt;, party_winning &lt;chr&gt;, tenure &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">incumbent_margin</span> <span class="op">~</span> <span class="va">party_incumbent</span>, <span class="va">us_elections</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = incumbent_margin ~ party_incumbent, data = us_elections)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.179  -7.824  -1.819   6.181  20.251 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)                  2.329      3.815   0.610    0.551
party_incumbentRepublican    3.436      5.243   0.655    0.522

Residual standard error: 10.79 on 15 degrees of freedom
Multiple R-squared:  0.02783,   Adjusted R-squared:  -0.03698 
F-statistic: 0.4294 on 1 and 15 DF,  p-value: 0.5222</code></pre>
</div>
</div>
<p>So far, we have tested the effect of two variables in two different models. However, we can also test the effect of two variables in a multiple linear regression model that allows us to control for the effect of other variables.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">incumbent_margin</span> <span class="op">~</span> <span class="va">income_growth</span> <span class="op">+</span> <span class="va">tenure</span>, <span class="va">us_elections</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = incumbent_margin ~ income_growth + tenure, data = us_elections)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.3524 -3.9170 -0.2879  2.5490  9.5650 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     9.9291     2.4632   4.031  0.00124 ** 
income_growth   5.4818     0.9193   5.963 3.47e-05 ***
tenure         -1.7636     0.2885  -6.113 2.68e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.097 on 14 degrees of freedom
Multiple R-squared:  0.7976,    Adjusted R-squared:  0.7686 
F-statistic: 27.58 on 2 and 14 DF,  p-value: 1.393e-05</code></pre>
</div>
</div>
<p>Lastly, we can also look at our results in a regression table with the <code>stargazer</code> package.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">stargazer</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/stargazer/man/stargazer.html">stargazer</a></span><span class="op">(</span></span>
<span>  <span class="va">model</span>,</span>
<span>  <span class="va">model2</span>,</span>
<span>  <span class="va">model3</span>, </span>
<span>  type <span class="op">=</span> <span class="st">"text"</span>,</span>
<span>  title <span class="op">=</span> <span class="st">"Economic voting : regression table"</span>,</span>
<span>  digits <span class="op">=</span> <span class="fl">2</span>,</span>
<span>  omit.stat <span class="op">=</span> <span class="st">"f"</span>,</span>
<span>  dep.var.labels <span class="op">=</span> <span class="st">"Margin of incumbent"</span>,</span>
<span>  covariate.labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Disposable Income"</span><span class="op">)</span>,</span>
<span>  <span class="co"># Put significance stars at 0.05, 0.01 and 0.001</span></span>
<span>  star.cutoffs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.05</span>, <span class="fl">0.01</span>, <span class="fl">0.001</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Economic voting : regression table
=======================================================================
                                       Dependent variable:             
                          ---------------------------------------------
                                       Margin of incumbent             
                               (1)             (2)            (3)      
-----------------------------------------------------------------------
Disposable Income             3.67*                         5.48***    
                              (1.61)                         (0.92)    
                                                                       
party_incumbentRepublican                     3.44                     
                                             (5.24)                    
                                                                       
tenure                                                      -1.76***   
                                                             (0.29)    
                                                                       
Constant                      -0.87           2.33           9.93**    
                              (3.18)         (3.81)          (2.46)    
                                                                       
-----------------------------------------------------------------------
Observations                    17             17              17      
R2                             0.26           0.03            0.80     
Adjusted R2                    0.21           -0.04           0.77     
Residual Std. Error       9.43 (df = 15) 10.79 (df = 15) 5.10 (df = 14)
=======================================================================
Note:                                     *p&lt;0.05; **p&lt;0.01; ***p&lt;0.001</code></pre>
</div>
</div>
</section><section id="your-turn" class="level1" data-number="10"><h1 data-number="10">
<span class="header-section-number">10</span> Your turn !</h1>
<p>So far, we have looked at the effect of the state of the economy and incumbent performance at the aggregate level with looking at different election results. But we could also look at this relationship at the individual level. For this, we can use the European Social Survey data that contains data on different socio-political attitudes of European citizens. Here, import the <code>ESS9e03_1.dta</code> file in the data folder and look at the relationship between satisfaction towards national government measured by the <code>stfgov</code> variable and satisfaction towards the economy in the country (socio-tropic evaluation) measured by the <code>stfeco</code> variable. You can also try with the hincfel variable as a categorical variable measuring how people feel about their household income (ego-tropic evaluation).</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://haven.tidyverse.org">haven</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">ess</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="st">"data/ESS9e03_1.dta"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ess</span> <span class="op">&lt;-</span> <span class="va">ess</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">stfeco</span>, <span class="va">stfgov</span>, <span class="va">hincfel</span><span class="op">)</span></span>
<span></span>
<span><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">stfgov</span> <span class="op">~</span> <span class="va">stfeco</span>, data <span class="op">=</span> <span class="va">ess</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = stfgov ~ stfeco, data = ess)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.4693 -1.1379  0.0633  1.3295  8.8621 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.137915   0.021304   53.41   &lt;2e-16 ***
stfeco      0.633134   0.003666  172.68   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.964 on 47015 degrees of freedom
  (2502 observations deleted due to missingness)
Multiple R-squared:  0.3881,    Adjusted R-squared:  0.3881 
F-statistic: 2.982e+04 on 1 and 47015 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ess</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">hincfel</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  hincfel                                          n
  &lt;dbl+lbl&gt;                                    &lt;int&gt;
1     1 [Living comfortably on present income] 15691
2     2 [Coping on present income]             22228
3     3 [Difficult on present income]           7972
4     4 [Very difficult on present income]      2930
5 NA(b) [Don't know]                             698</code></pre>
</div>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">stfgov</span> <span class="op">~</span> <span class="va">hincfel</span>, data <span class="op">=</span> <span class="va">ess</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = stfgov ~ hincfel, data = ess)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.0093 -1.8639  0.1361  1.9907  6.7088 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.58195    0.02856  195.48   &lt;2e-16 ***
hincfel     -0.57268    0.01341  -42.71   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.466 on 47181 degrees of freedom
  (2336 observations deleted due to missingness)
Multiple R-squared:  0.03723,   Adjusted R-squared:  0.03721 
F-statistic:  1824 on 1 and 47181 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ess</span> <span class="op">&lt;-</span> <span class="va">ess</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    hincfel_cat <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span></span>
<span>      <span class="va">hincfel</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">~</span> <span class="st">"Comfortably"</span>,</span>
<span>      <span class="va">hincfel</span> <span class="op">==</span> <span class="fl">2</span> <span class="op">~</span> <span class="st">"Coping"</span>,</span>
<span>      <span class="va">hincfel</span> <span class="op">==</span> <span class="fl">3</span> <span class="op">~</span> <span class="st">"Difficult"</span>,</span>
<span>      <span class="va">hincfel</span> <span class="op">==</span> <span class="fl">4</span> <span class="op">~</span> <span class="st">"Very difficult"</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">m3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">stfgov</span> <span class="op">~</span> <span class="va">hincfel_cat</span>, data <span class="op">=</span> <span class="va">ess</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m3</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = stfgov ~ hincfel_cat, data = ess)

Residuals:
   Min     1Q Median     3Q    Max 
-5.021 -1.877  0.123  1.980  6.696 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                5.02047    0.01994  251.77   &lt;2e-16 ***
hincfel_catCoping         -0.59814    0.02608  -22.93   &lt;2e-16 ***
hincfel_catDifficult      -1.14349    0.03455  -33.10   &lt;2e-16 ***
hincfel_catVery difficult -1.71625    0.05109  -33.59   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.466 on 47179 degrees of freedom
  (2336 observations deleted due to missingness)
Multiple R-squared:  0.03726,   Adjusted R-squared:  0.0372 
F-statistic: 608.6 on 3 and 47179 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/malojan\.github\.io\/introduction-r\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../session04/04_relationships.html" class="pagination-link" aria-label="Testing relationships">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Testing relationships</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../session06/06_modelling.html" class="pagination-link" aria-label="Multivariate Relationships">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Multivariate Relationships</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/malojan/introduction-r/edit/main/session05/correlation_regression.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>