<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.41">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Introduction to R – 7&nbsp; Testing relationships</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../session05/correlation_regression.html" rel="next">
<link href="../session03/03_dataviz.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../session04/04_relationships.html">Testing relationships</a></li><li class="breadcrumb-item"><a href="../session04/04_relationships.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Testing relationships</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introduction to R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/malojan/introduction-r" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Setting up R and Rstudio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting started with R and Rstudio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session01/workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Rstudio, scripts, quarto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session01/basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session01/help.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Getting help and dealing with errors</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Manipulating and describing data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session02/0201_manipulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Manipulating data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session02/0202_reshape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reshaping data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Visualizing data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session03/03_dataviz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data visualization</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Testing relationships</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session04/04_relationships.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Testing relationships</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Regression analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session05/correlation_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exploring correlations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Multivariate analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../session06/06_modelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Multivariate Relationships</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#joining-datasets" id="toc-joining-datasets" class="nav-link active" data-scroll-target="#joining-datasets"><span class="header-section-number">7.1</span> Joining datasets</a></li>
  <li><a href="#renaming-variables" id="toc-renaming-variables" class="nav-link" data-scroll-target="#renaming-variables"><span class="header-section-number">7.2</span> Renaming variables</a></li>
  <li><a href="#recoding-variables" id="toc-recoding-variables" class="nav-link" data-scroll-target="#recoding-variables"><span class="header-section-number">7.3</span> Recoding variables</a></li>
  <li><a href="#dealing-with-nas" id="toc-dealing-with-nas" class="nav-link" data-scroll-target="#dealing-with-nas"><span class="header-section-number">7.4</span> Dealing with Nas</a></li>
  <li><a href="#relationships-between-two-categorical-variables-%CF%87%C2%B2-test" id="toc-relationships-between-two-categorical-variables-χ²-test" class="nav-link" data-scroll-target="#relationships-between-two-categorical-variables-%CF%87%C2%B2-test"><span class="header-section-number">7.5</span> Relationships between two categorical variables : χ² test</a></li>
  <li><a href="#relationship-between-a-categorical-and-a-continuous-variable-t-test" id="toc-relationship-between-a-categorical-and-a-continuous-variable-t-test" class="nav-link" data-scroll-target="#relationship-between-a-categorical-and-a-continuous-variable-t-test"><span class="header-section-number">7.6</span> Relationship between a categorical and a continuous variable : t-test</a></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn"><span class="header-section-number">8</span> Your turn</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/malojan/introduction-r/edit/main/session04/04_relationships.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../session04/04_relationships.html">Testing relationships</a></li><li class="breadcrumb-item"><a href="../session04/04_relationships.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Testing relationships</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Testing relationships</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In social sciences, our primary interest lies in understanding how certain variables vary across different groups. This session focuses primarily on bivariate relationships. When analyzing data, our objective often is to measure the association between two variables. For example, are men more likely to vote for radical right parties than women? Do autocratic regimes engage in warfare more frequently than democracies? Do individuals with more information tend to hold stronger beliefs in the reality of climate change than those without? In this context, we focus solely on relationships, not causality. Investigating causality would entail understanding the exact nature of the relationship and accounting for other variables that may influence this association.</p>
<p>When examining these relationships, our primary concern is statistical inference. Typically, our analysis is based on a sample taken from the population under study, meaning that our results are contingent on this specific sample. However, our ultimate goal is to make general statements or draw conclusions about the larger population. To determine whether the observed association in our data can be generalized, we need to conduct statistical tests. Our sample gives us an estimate of the “true” population relationship, and statistical tests assess how confident we can be that the association we observe is not simply due to sampling variability. By performing these statistical tests, we can make more reliable inferences about the broader population based on the sample we have analyzed.</p>
<p>We aim to determine whether the relationship observed in the data is real or merely the result of random chance. To do this, we formulate a null hypothesis: that the observed relationship is due to random chance. Typically, we seek to reject this null hypothesis and provide evidence for our alternative hypothesis that this effect is not random. To achieve this, we conduct a statistical test that yields a p-value: the probability of observing an association at least as strong as the one in our data if the null hypothesis were true.</p>
<p>To explore how to do this in R, we will use data from the 2022 French electoral study. This dataset was collected following the last French presidential election and contains variables on voting behavior. Before testing the relationship between different variables, I will cover various data wrangling steps that are often necessary before analyzing the data, such as joining data frames, recoding variables, and managing missing values.</p>
<section id="joining-datasets" class="level2" data-number="7.1"><h2 data-number="7.1" class="anchored" data-anchor-id="joining-datasets">
<span class="header-section-number">7.1</span> Joining datasets</h2>
<p>In many instances, we encounter data originating from different datasets that share common variables. In this context, I have two datasets concerning French voters. The first dataset is an annual survey that comprises information regarding the socio-demographic characteristics of the respondents. The second dataset is a panel survey conducted during the most recent presidential election, providing data about the voting choices of the respondents. Both datasets pertain to the same individuals and include a unique identifier (UID) that enables us to correlate the two datasets. Our objective is to amalgamate these two datasets into a single one that encompasses both the socio-demographic characteristics and the voting choices of the respondents. To accomplish this, we must merge the two datasets. Note that this is different from binding datasets together as we already did before with <code><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows()</a></code> where we binded datasets having the same columns but not the same observations.</p>
<p>Let’s start by loading a bunch of packages we will use today and the two datasets I just described.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load packages (install.packages("package_name") if you don't have them installed yet</span></span>
<span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/sfirke/janitor">janitor</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://haven.tidyverse.org">haven</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://larmarange.github.io/labelled/">labelled</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/infer">infer</a></span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co"># Load the data</span></span>
<span></span>
<span><span class="va">fes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="st">"fes2022v4bis.dta"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">annual</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://haven.tidyverse.org/reference/read_dta.html">read_dta</a></span><span class="op">(</span><span class="st">"elipss_annual.dta"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To join them together, we will use the <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> function from the <code>dplyr</code> package. This function is used to combine two datasets by matching the values of one or more variables in each dataset. The first dataset is the one that we want to keep all the observations from. The second dataset is the one that we want to add observations from. In our case, we want to keep all the observations from the fes dataset and add the variables from the annual dataset. The <code>by</code> argument specifies the variable(s) that will be used to match observations in the two datasets. In our case, we will use the <code>UID</code> variable that is common to both datasets.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">fes</span>, <span class="va">annual</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"UID"</span><span class="op">)</span><span class="op">)</span> <span class="co"># Join the two datasets by the UID variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> function is indeed one of the most commonly used methods for joining data in R. However, it’s important to note that there are several other types of joins that can be applied, each with its own specific use case. If you’d like to delve deeper into how these joins work, I recommend checking out the<a href="https://r4ds.hadley.nz/joins.html">R for data science book’s</a> explanation of these concepts. These diagrams below shows the different types of joins that can be performed with the <code>dplyr</code> package.</p>
<p><img src="https://r4ds.hadley.nz/diagrams/join/venn.png" class="img-fluid"></p>
<p>If we check the names of our columns, we can now see that we have in our new dataset, the columns of both previous datasets with the same number of observations.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">fes2022</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "UID"                   "fes4_Q01"              "fes4_Q02a"            
  [4] "fes4_Q02b"             "fes4_Q02c"             "fes4_Q02d"            
  [7] "fes4_Q02e"             "fes4_Q02f"             "fes4_Q02g"            
 [10] "fes4_Q03"              "fes4_Q04a"             "fes4_Q04b"            
 [13] "fes4_Q04c"             "fes4_Q04d"             "fes4_Q04_DO_Q04a"     
 [16] "fes4_Q04_DO_Q04b"      "fes4_Q04_DO_Q04c"      "fes4_Q04_DO_Q04d"     
 [19] "fes4_Q05a"             "fes4_Q05b"             "fes4_Q05c"            
 [22] "fes4_Q05_DO_Q05a"      "fes4_Q05_DO_Q05b"      "fes4_Q05_DO_Q05c"     
 [25] "fes4_Q06"              "fes4_Q07a"             "fes4_Q07b"            
 [28] "fes4_Q07d"             "fes4_Q07e"             "fes4_Q07f"            
 [31] "fes4_Q07g"             "fes4_Q07_DO_Q07a"      "fes4_Q07_DO_Q07b"     
 [34] "fes4_Q07_DO_Q07c"      "fes4_Q07_DO_Q07d"      "fes4_Q07_DO_Q07e"     
 [37] "fes4_Q07_DO_Q07f"      "fes4_Q07_DO_Q07g"      "fes4_Q08a"            
 [40] "fes4_Q08b"             "fes4_Q09"              "fes4_Q10p1_a"         
 [43] "fes4_Q10p1_b"          "fes4_Q10p2_a"          "fes4_Q10p2_b"         
 [46] "fes4_Q10lh1_a"         "fes4_Q10lh1_c"         "fes4_Q11a"            
 [49] "fes4_Q11b"             "fes4_Q11c"             "fes4_Q12"             
 [52] "fes4_Q13"              "fes4_Q14a"             "fes4_Q14b"            
 [55] "fes4_Q14c"             "fes4_Q14d"             "fes4_Q15"             
 [58] "fes4_Q16a"             "fes4_Q16b"             "fes4_Q16c"            
 [61] "fes4_Q16d"             "fes4_Q16e"             "fes4_Q16f"            
 [64] "fes4_Q16g"             "fes4_Q16h"             "fes4_Q17a"            
 [67] "fes4_Q17b"             "fes4_Q17c"             "fes4_Q17d"            
 [70] "fes4_Q17e"             "fes4_Q17f"             "fes4_Q18a"            
 [73] "fes4_Q18b"             "fes4_Q18c"             "fes4_Q18d"            
 [76] "fes4_Q18e"             "fes4_Q18f"             "fes4_Q18g"            
 [79] "fes4_Q18h"             "fes4_Q19"              "fes4_Q22"             
 [82] "fes4_Q23a"             "fes4_Q23b"             "fes4_Q23c"            
 [85] "fes4_Q23d"             "fes4_Q24"              "fes4_Q25a"            
 [88] "fes4_Q25b"             "fes4_Q26a"             "fes4_Q26b"            
 [91] "fes4_Q27a"             "fes4_Q27b"             "fes4_Q27c"            
 [94] "fes4_Q27d"             "fes4_bloc_q25_DO_Q25a" "fes4_bloc_q25_DO_Q25b"
 [97] "fes4_bloc_q26_DO_Q26a" "fes4_bloc_q26_DO_Q26b" "cal_AGE"              
[100] "cal_DIPL"              "cal_SEXE"              "cal_TUU"              
[103] "cal_ZEAT"              "cal_AGE1"              "cal_AGE2"             
[106] "cal_NAT"               "cal_DIPL2"             "panel"                
[109] "VAGUE"                 "POIDS_fes4"            "PDSPLT1_fes4"         
[112] "PDSPLT2_fes4"          "POIDS_INIT"            "PDSPLT_INIT1"         
[115] "PDSPLT_INIT2"          "eayy_a1"               "eayy_a2a_rec"         
[118] "eayy_a2a_rec2"         "eayy_a3_rec"           "eayy_a3b_rec"         
[121] "eayy_a3c_rec"          "eayy_a3d"              "eayy_a3e_rec"         
[124] "eayy_a4"               "eayy_a5"               "eayy_a5c_rec"         
[127] "eayy_b1"               "eayy_b1_rev"           "eayy_b1_sc"           
[130] "eayy_b1_sccjt"         "eayy_b10a"             "eayy_b10aa"           
[133] "eayy_b10acjt"          "eayy_b11"              "eayy_b11cjt"          
[136] "eayy_b18_rec"          "eayy_b18c"             "eayy_b18ccjt"         
[139] "eayy_b18cjt_rec"       "eayy_b1a"              "eayy_b1acjt"          
[142] "eayy_b1b"              "eayy_b1bcjt"           "eayy_b1cjt"           
[145] "eayy_b1cjt_rev"        "eayy_b2_11a_rec"       "eayy_b2_11acjt_rec"   
[148] "eayy_b2_rec"           "eayy_b25"              "eayy_b25_rec"         
[151] "eayy_b25cjt_rec"       "eayy_b2cjt_rec"        "eayy_b4_rec"          
[154] "eayy_b4cjt_rec"        "eayy_b5"               "eayy_b5_rec"          
[157] "eayy_b5a"              "eayy_b5a_rec"          "eayy_b5acjt"          
[160] "eayy_b5c"              "eayy_b5c_rec"          "eayy_b5ccjt"          
[163] "eayy_b5d_rec"          "eayy_b6a_12a_rec"      "eayy_b6a_rec"         
[166] "eayy_b6b_12b_rec"      "eayy_b6b_rec"          "eayy_b7b_rec"         
[169] "eayy_b8_rec"           "eayy_b8cjt_rec"        "eayy_c1_rec"          
[172] "eayy_c1jeu"            "eayy_c8"               "eayy_c8a_rec"         
[175] "eayy_c8b_rec"          "eayy_d1"               "eayy_d1_rec"          
[178] "eayy_d2"               "eayy_d2_rev"           "eayy_d3"              
[181] "eayy_d4_rec"           "eayy_d5_rec"           "eayy_d6"              
[184] "eayy_d7_1"             "eayy_d7_10"            "eayy_d7_2"            
[187] "eayy_d7_3"             "eayy_d7_4"             "eayy_d7_5"            
[190] "eayy_d7_6"             "eayy_d7_7"             "eayy_d7_8"            
[193] "eayy_d7_9"             "eayy_d7_rev_1"         "eayy_d7_rev_10"       
[196] "eayy_d7_rev_11"        "eayy_d7_rev_2"         "eayy_d7_rev_3"        
[199] "eayy_d7_rev_4"         "eayy_d7_rev_5"         "eayy_d7_rev_6"        
[202] "eayy_d7_rev_7"         "eayy_d7_rev_8"         "eayy_d7_rev_9"        
[205] "eayy_e1a_rec"          "eayy_e1b_rec"          "eayy_e1c_rec"         
[208] "eayy_e1d_rec"          "eayy_e1e_rec"          "eayy_e1f"             
[211] "eayy_e1f1_rec"         "eayy_e1f2_rec"         "eayy_e1g_rec"         
[214] "eayy_e1h_rec"          "eayy_e1i_rec"          "eayy_e1j_rec"         
[217] "eayy_e2a_rec"          "eayy_e2auc"            "eayy_e2auc_source"    
[220] "eayy_e3a"              "eayy_e3b"              "eayy_e3c"             
[223] "eayy_e3d"              "eayy_e3e"              "eayy_e4"              
[226] "eayy_e5"               "eayy_e6"               "eayy_f1_rec"          
[229] "eayy_f1_rev"           "eayy_f1a1"             "eayy_f3"              
[232] "eayy_f3_rev"           "eayy_f4"               "eayy_f6_rec"          
[235] "eayy_f6a"              "eayy_f7"               "eayy_f7_1"            
[238] "eayy_f7_10"            "eayy_f7_11"            "eayy_f7_12"           
[241] "eayy_f7_13"            "eayy_f7_14"            "eayy_f7_15"           
[244] "eayy_f7_2"             "eayy_f7_3"             "eayy_f7_4"            
[247] "eayy_f7_5"             "eayy_f7_6"             "eayy_f7_8"            
[250] "eayy_f7_9"             "eayy_f7bis_1"          "eayy_f7bis_10"        
[253] "eayy_f7bis_11"         "eayy_f7bis_12"         "eayy_f7bis_13"        
[256] "eayy_f7bis_14"         "eayy_f7bis_2"          "eayy_f7bis_3"         
[259] "eayy_f7bis_4"          "eayy_f7bis_5"          "eayy_f7bis_6"         
[262] "eayy_f7bis_7"          "eayy_f7bis_8"          "eayy_f7bis_9"         
[265] "eayy_f8"               "eayy_f9"               "eayy_g1"              
[268] "eayy_g1_1"             "eayy_g1_2"             "eayy_g10"             
[271] "eayy_g2"               "eayy_g3a"              "eayy_g3b"             
[274] "eayy_g3c"              "eayy_g3d"              "eayy_g4"              
[277] "eayy_g5"               "eayy_g6_1"             "eayy_g6_2"            
[280] "eayy_g6_3"             "eayy_g6_4"             "eayy_h_c11"           
[283] "eayy_h_teo1"           "eayy_h1a"              "eayy_h4"              
[286] "eayy_i1"               "eayy_i13a"             "eayy_i13b"            
[289] "eayy_i2"               "eayy_i8"               "eayy_j1"              
[292] "eayy_k3"               "eayy_pcs18"            "eayy_pcs6"            
[295] "eayy_pcs6cjt"          "eayy_typmen5"         </code></pre>
</div>
</div>
</section><section id="renaming-variables" class="level2" data-number="7.2"><h2 data-number="7.2" class="anchored" data-anchor-id="renaming-variables">
<span class="header-section-number">7.2</span> Renaming variables</h2>
<p>Our examination of the column names also reveals that the variable names are not particularly informative. It can be challenging to discern the specific information represented by each variable. Today, I am interested in the relationship between education levels and voting behavior in the second round of the election. So I rename these two variables with more informative names. I also rename other variables on sympathy towards candidates that I will use late.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span></span>
<span>    gender <span class="op">=</span> <span class="va">cal_SEXE</span>, <span class="co"># Gender variable</span></span>
<span>    education <span class="op">=</span> <span class="va">cal_DIPL</span>, <span class="co"># Education variable</span></span>
<span>    vote_t2 <span class="op">=</span> <span class="va">fes4_Q10p2_b</span>, <span class="co"># Vote at the second round of the election</span></span>
<span>    symp_macron <span class="op">=</span> <span class="va">fes4_Q17a</span>, <span class="co"># Sympathy towards Macron </span></span>
<span>    symp_lepen <span class="op">=</span> <span class="va">fes4_Q17d</span>, <span class="co"># Sympathy towards Le Pen (Far right)</span></span>
<span>    symp_zemmour <span class="op">=</span> <span class="va">fes4_Q17b</span>, <span class="co"># Sympathy towards Zemmour (Far right)</span></span>
<span>    symp_melenchon <span class="op">=</span> <span class="va">fes4_Q17c</span>, <span class="co"># Sympathy towards Mélenchon (Radical left)</span></span>
<span>    symp_jadot <span class="op">=</span> <span class="va">fes4_Q17f</span> <span class="co"># Sympathy towards Jadot (Greens)</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="recoding-variables" class="level2" data-number="7.3"><h2 data-number="7.3" class="anchored" data-anchor-id="recoding-variables">
<span class="header-section-number">7.3</span> Recoding variables</h2>
<p>In addition to renaming variables, we may also need to recode variables. Let’s look at these two variables. Education is coded in four different categories but the actual values are numbers from 1 to 4 and we migh want a categorical variable with the labels instead. Moreoever, I also want to change the order of the categories to have the less educated people first and the more educated people last.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">education</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  education                           n
  &lt;dbl+lbl&gt;                       &lt;int&gt;
1 1 [Diplôme supérieur]             829
2 2 [BAC et BAC+2]                  286
3 3 [CAP + BEPC]                    352
4 4 [Sans diplôme et non déclaré]   108</code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    <span class="co"># Convert the education variable values by their labels</span></span>
<span>    education <span class="op">=</span> <span class="fu"><a href="https://larmarange.github.io/labelled/reference/to_factor.html">unlabelled</a></span><span class="op">(</span><span class="va">education</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>      <span class="co"># Change the order of the categories</span></span>
<span>      <span class="fu"><a href="https://forcats.tidyverse.org/reference/fct_relevel.html">fct_relevel</a></span><span class="op">(</span></span>
<span>        <span class="st">"Sans diplôme et non déclaré"</span>,</span>
<span>        <span class="st">"CAP + BEPC"</span>,</span>
<span>        <span class="st">"BAC et BAC+2"</span>,</span>
<span>        <span class="st">"Diplôme supérieur"</span></span>
<span>      <span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">education</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  education                       n
  &lt;fct&gt;                       &lt;int&gt;
1 Sans diplôme et non déclaré   108
2 CAP + BEPC                    352
3 BAC et BAC+2                  286
4 Diplôme supérieur             829</code></pre>
</div>
</div>
<p>Our vote variable at the second round is also coded with values from 1 to 4. We might want to recode it to have the names of the candidates instead of numbers, and to have a single category for the people who did not cast a valid vote.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">vote_t2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  vote_t2                                                     n
  &lt;dbl+lbl&gt;                                               &lt;int&gt;
1     1 [Marine Le Pen, Rassemblement national (RN)]        270
2     2 [Emmanuel Macron, La République en marche (LREM)]   808
3     3 [Vous avez voté blanc]                              164
4     4 [Vous avez voté nul]                                 39
5 NA(a)                                                     294</code></pre>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Recode vote_t2</span></span>
<span><span class="va">fes2022</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    <span class="co"># Create a new variable called candidate_t2</span></span>
<span>    candidate_t2 <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span></span>
<span>      <span class="co"># When vote_t2 is 1, assign the value "Le Pen"</span></span>
<span>      <span class="va">vote_t2</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">~</span> <span class="st">"Le Pen"</span>,</span>
<span>      <span class="co"># When vote_t2 is 2, assign the value "Macron"</span></span>
<span>      <span class="va">vote_t2</span> <span class="op">==</span> <span class="fl">2</span> <span class="op">~</span> <span class="st">"Macron"</span>,</span>
<span>      <span class="co"># When vote_t2 is 3 or 4, assign the value "No valid vote"</span></span>
<span>      <span class="va">vote_t2</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span> <span class="op">~</span> <span class="st">"No valid vote"</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">vote_t2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  vote_t2                                                     n
  &lt;dbl+lbl&gt;                                               &lt;int&gt;
1     1 [Marine Le Pen, Rassemblement national (RN)]        270
2     2 [Emmanuel Macron, La République en marche (LREM)]   808
3     3 [Vous avez voté blanc]                              164
4     4 [Vous avez voté nul]                                 39
5 NA(a)                                                     294</code></pre>
</div>
</div>
</section><section id="dealing-with-nas" class="level2" data-number="7.4"><h2 data-number="7.4" class="anchored" data-anchor-id="dealing-with-nas">
<span class="header-section-number">7.4</span> Dealing with Nas</h2>
<p>In the last code chunk, it became evident that our “vote” variable contains a considerable number of missing values Before we go further, I want to take a moment to discuss how to deal with missing values. Initially, it’s advisable to obtain an overview of the extent of missing values within our dataset.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">fes2022</span><span class="op">)</span><span class="op">)</span> <span class="co"># Count the total number of missing values in the dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 97557</code></pre>
</div>
</div>
<p>We see that we actually have a lot of missing values. This is because some of the variables are only asked to a subset of the respondents. There are several ways to deal with it depending on what you want to do :</p>
<ul>
<li>Removing Nas</li>
<li>Converting values to Nas</li>
<li>Replacing Nas</li>
</ul>
<p>First, in some instances, we might want to consider to remove all of the observations that have Nas. You can do that by using <code><a href="https://tidyr.tidyverse.org/reference/drop_na.html">tidyr::drop_na()</a></code> on the whole dataset. But be careful with this ! You might lose a lot of information. Here, we actually end up with 0 observations because all of our observations have missing values in at least one variable.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Drop all of the observations that have missing values</span></span>
<span><span class="va">fes_without_nas</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Drop all of the observations that have missing values in the variable symp_macron</span></span>
<span></span>
<span><span class="va">fes_without_nas</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="va">symp_macron</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we might want to convert some values to Nas. We can do that by using the <code><a href="https://dplyr.tidyverse.org/reference/na_if.html">dplyr::na_if()</a></code> function. Here, for instance, I have a variable <code>symp_macron</code> containing information on sympathy towards Emmanuel Macron. The value 96 corresponds to “I don’t know him”. The problem with keeping this value is that it is not a missing value and it will be included in the analysis. For instance, if I compute a mean on this variable, the value 96 will be included in the computation.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">symp_macron</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
   symp_macron                                            n
   &lt;dbl+lbl&gt;                                          &lt;int&gt;
 1     0 [Je n'aime pas du tout cette personnalité 0]   308
 2     1 [1]                                             89
 3     2 [2]                                             98
 4     3 [3]                                            109
 5     4 [4]                                            105
 6     5 [5]                                            202
 7     6 [6]                                            135
 8     7 [7]                                            170
 9     8 [8]                                            155
10     9 [9]                                             78
11    10 [J'aime beaucoup cette personnalité 10]        101
12    96 [Je ne connais pas cette personnalité]           6
13 NA(a)                                                 19</code></pre>
</div>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">fes2022</span><span class="op">$</span><span class="va">symp_macron</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.865039</code></pre>
</div>
</div>
<p>To avoid this, we can convert the value 96 to NA with <code><a href="https://dplyr.tidyverse.org/reference/na_if.html">na_if()</a></code>. As we can see, the value 96 is now considered as a missing value and is not included in the computation of the mean that is now 4.51.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes_recoded</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>symp_macron <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/na_if.html">na_if</a></span><span class="op">(</span><span class="va">symp_macron</span>, <span class="fl">96</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fes_recoded</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">symp_macron</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   symp_macron                                         n
   &lt;dbl+lbl&gt;                                       &lt;int&gt;
 1  0 [Je n'aime pas du tout cette personnalité 0]   308
 2  1 [1]                                             89
 3  2 [2]                                             98
 4  3 [3]                                            109
 5  4 [4]                                            105
 6  5 [5]                                            202
 7  6 [6]                                            135
 8  7 [7]                                            170
 9  8 [8]                                            155
10  9 [9]                                             78
11 10 [J'aime beaucoup cette personnalité 10]        101
12 NA                                                 25</code></pre>
</div>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">fes_recoded</span><span class="op">$</span><span class="va">symp_macron</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.512258</code></pre>
</div>
</div>
<p>You can also automate this with the <code><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_at()</a></code> function. Here, I convert all of the values 96 in the variables starting with “symp” to NAs.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Automation on all of the candidates</span></span>
<span></span>
<span><span class="va">fes2022</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_at</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/vars.html">vars</a></span><span class="op">(</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"symp"</span><span class="op">)</span><span class="op">)</span>, <span class="op">~</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/na_if.html">na_if</a></span><span class="op">(</span><span class="va">.</span>, <span class="fl">96</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we might want to replace Nas with other values. For instance the vote for the secound round variable has missing values as some people did not vote or refused to answer. I might want to keep those values and replace them by another value. Here I decide to code them as well as “No valid vote” which will contains all of the people that did not cast a valid vote (Macron or Le Pen). We can do that by using the <code><a href="https://tidyr.tidyverse.org/reference/replace_na.html">tidyr::replace_na()</a></code> function.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">candidate_t2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  candidate_t2      n
  &lt;chr&gt;         &lt;int&gt;
1 Le Pen          270
2 Macron          808
3 No valid vote   203
4 &lt;NA&gt;            294</code></pre>
</div>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>candidate_t2 <span class="op">=</span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/replace_na.html">replace_na</a></span><span class="op">(</span><span class="va">candidate_t2</span>, <span class="st">"No valid vote"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">candidate_t2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  candidate_t2      n
  &lt;chr&gt;         &lt;int&gt;
1 Le Pen          270
2 Macron          808
3 No valid vote   497</code></pre>
</div>
</div>
<p>If you want to delve deeper into the topic of missing values, I recommend you to read <a href="https://r4ds.hadley.nz/missing-values">this</a>. Also, note that there are other ways to deal with missing values. For instance, you can use imputation techniques to replace missing values by plausible values.</p>
</section><section id="relationships-between-two-categorical-variables-χ²-test" class="level2" data-number="7.5"><h2 data-number="7.5" class="anchored" data-anchor-id="relationships-between-two-categorical-variables-χ²-test">
<span class="header-section-number">7.5</span> Relationships between two categorical variables : χ² test</h2>
<p>Let’s look a the relatiohship between two variables : education and voting choice at the second round of the 2022 presidential election. We want to know if there is a relationship between these two variables. We can then formulate the following hypotheses :</p>
<p>H0 (null hypothesis) : There is NO relationship between education levels and voting choice</p>
<p>H1 : There is a relationship between education levels and voting choice</p>
<p>To look at the plausible relationship between these two variables, we can create a contingency table (or crosstab). Here I use the<code><a href="https://sfirke.github.io/janitor/reference/tabyl.html">janitor::tabyl()</a></code> function. But you can also use the <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> function from base R. These table show the distribution of voting choice for each level of education.</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Create a contingency table</span></span>
<span><span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/tabyl.html">tabyl</a></span><span class="op">(</span><span class="va">candidate_t2</span>, <span class="va">education</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  candidate_t2 Sans diplôme et non déclaré CAP + BEPC BAC et BAC+2
        Le Pen                          29         89           50
        Macron                          39        141          133
 No valid vote                          40        122          103
 Diplôme supérieur
               102
               495
               232</code></pre>
</div>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Format the table to add totals and percentages</span></span>
<span></span>
<span><span class="va">contingency_table</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/tabyl.html">tabyl</a></span><span class="op">(</span><span class="va">candidate_t2</span>, <span class="va">education</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="co"># Create a contingency table</span></span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/adorn_totals.html">adorn_totals</a></span><span class="op">(</span><span class="st">"row"</span><span class="op">)</span> <span class="op">|&gt;</span>  <span class="co"># Add totals as last row </span></span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/adorn_totals.html">adorn_totals</a></span><span class="op">(</span><span class="st">"col"</span><span class="op">)</span> <span class="op">|&gt;</span>  <span class="co"># Add totals as last column</span></span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/adorn_percentages.html">adorn_percentages</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="co"># Convert to percentages</span></span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/adorn_pct_formatting.html">adorn_pct_formatting</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">|&gt;</span>  </span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/adorn_ns.html">adorn_ns</a></span><span class="op">(</span><span class="op">)</span>  </span>
<span></span>
<span><span class="va">contingency_table</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  candidate_t2 Sans diplôme et non déclaré  CAP + BEPC BAC et BAC+2
        Le Pen                 10.7%  (29) 33.0%  (89)  18.5%  (50)
        Macron                  4.8%  (39) 17.5% (141)  16.5% (133)
 No valid vote                  8.0%  (40) 24.5% (122)  20.7% (103)
         Total                  6.9% (108) 22.3% (352)  18.2% (286)
 Diplôme supérieur          Total
       37.8% (102) 100.0%   (270)
       61.3% (495) 100.0%   (808)
       46.7% (232) 100.0%   (497)
       52.6% (829) 100.0% (1,575)</code></pre>
</div>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Alternative way with base R </span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">fes2022</span><span class="op">$</span><span class="va">candidate_t2</span>, <span class="va">fes2022</span><span class="op">$</span><span class="va">education</span><span class="op">)</span> <span class="co"># Create a contingency table</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
                Sans diplôme et non déclaré CAP + BEPC BAC et BAC+2
  Le Pen                                 29         89           50
  Macron                                 39        141          133
  No valid vote                          40        122          103
               
                Diplôme supérieur
  Le Pen                      102
  Macron                      495
  No valid vote               232</code></pre>
</div>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">fes2022</span><span class="op">$</span><span class="va">candidate_t2</span>, <span class="va">fes2022</span><span class="op">$</span><span class="va">education</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
                Sans diplôme et non déclaré CAP + BEPC BAC et BAC+2
  Le Pen                         0.10740741 0.32962963   0.18518519
  Macron                         0.04826733 0.17450495   0.16460396
  No valid vote                  0.08048290 0.24547284   0.20724346
               
                Diplôme supérieur
  Le Pen               0.37777778
  Macron               0.61262376
  No valid vote        0.46680080</code></pre>
</div>
</div>
<p>From this table, we can already see that the vote choice vary across education level. The total shows us what would be the distribution of voting choice if there was no relationship between education and voting choice. But we can see that voters with higher education have voted more for Macron than for Le Pen and that the opposite is true for voters with lower education. But is this difference statistically significant or does it reflect sampling error ?</p>
<p>To test this, we need to compute a test statistic. As we ar dealing with two categorical variables, we will use a <code>χ²</code> test. This test is used to test the relationship between two categorical variables by comparing the observed distribution of our values to their expected distribution if there was no relationship between the two variables. To do this in R, we can use the <code><a href="https://sfirke.github.io/janitor/reference/chisq.test.html">chisq.test()</a></code> function. By default, the significance level is set at 0.05.</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_educ</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://sfirke.github.io/janitor/reference/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">fes2022</span><span class="op">$</span><span class="va">candidate_t2</span>, <span class="va">fes2022</span><span class="op">$</span><span class="va">education</span><span class="op">)</span></span>
<span></span>
<span><span class="va">test_educ</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  fes2022$candidate_t2 and fes2022$education
X-squared = 64.386, df = 6, p-value = 5.757e-12</code></pre>
</div>
</div>
<p>This gives us several informations :</p>
<ul>
<li>The X-squared value, which is our test statistic. It is computed by comparing the observed values to the expected values. You can access them with <code><a href="https://generics.r-lib.org/reference/augment.html">broom::augment()</a></code>. Expected values are the values that we would expect if there was no relationship between the two variables. They are computed by multiplying the row total by the column total and dividing by the grand total. Ex, for Le Pen and less educated : 270*108/1575 = 18.51. If there was no relationship between education and voting choice, we would expect about 18.5 people without a diploma to vote for Le Pen, and we observe 29.</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">augmented_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="va">test_educ</span><span class="op">)</span></span>
<span></span>
<span><span class="va">augmented_test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 9
   fes2022.candidate_t2 fes2022.education   .observed  .prop .row.prop .col.prop
   &lt;fct&gt;                &lt;fct&gt;                   &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 Le Pen               Sans diplôme et no…        29 0.0184    0.107      0.269
 2 Macron               Sans diplôme et no…        39 0.0248    0.0483     0.361
 3 No valid vote        Sans diplôme et no…        40 0.0254    0.0805     0.370
 4 Le Pen               CAP + BEPC                 89 0.0565    0.330      0.253
 5 Macron               CAP + BEPC                141 0.0895    0.175      0.401
 6 No valid vote        CAP + BEPC                122 0.0775    0.245      0.347
 7 Le Pen               BAC et BAC+2               50 0.0317    0.185      0.175
 8 Macron               BAC et BAC+2              133 0.0844    0.165      0.465
 9 No valid vote        BAC et BAC+2              103 0.0654    0.207      0.360
10 Le Pen               Diplôme supérieur         102 0.0648    0.378      0.123
11 Macron               Diplôme supérieur         495 0.314     0.613      0.597
12 No valid vote        Diplôme supérieur         232 0.147     0.467      0.280
# ℹ 3 more variables: .expected &lt;dbl&gt;, .resid &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Compute chi2 value</span></span>
<span></span>
<span><span class="va">chi2_value</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">(</span><span class="va">augmented_test</span><span class="op">$</span><span class="va">.observed</span> <span class="op">-</span> <span class="va">augmented_test</span><span class="op">$</span><span class="va">.expected</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="va">augmented_test</span><span class="op">$</span><span class="va">.expected</span><span class="op">)</span></span>
<span><span class="va">chi2_value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 64.38626</code></pre>
</div>
</div>
<p>We use the conventional significance level of 0.05: we reject the null hypothesis if the p-value is below 0.05. The p-value is the probability of observing a test statistic as extreme or more extreme than the one we observed if the null hypothesis is true. It is computed from the X-squared value and the degrees of freedom of the χ² distribution. Here, the p-value is 5.757e-12, which is equivalent to 0.000000000005757. This means that if there was no relationship between education and voting choice in the population, we would observe an association at least this strong in our sample only 0.0000000005757% of the time. So we can reject the null hypothesis and conclude that there is a statistically significant relationship between education and voting choice.</p>
<p>Using the <code>infer</code> package, we can also visualize how far is our observed statistic from the distribution of statistics under the null hypothesis.</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># calculate the observed statistic</span></span>
<span></span>
<span><span class="va">observed_indep_statistic</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/specify.html">specify</a></span><span class="op">(</span><span class="va">candidate_t2</span> <span class="op">~</span> <span class="va">education</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/hypothesize.html">hypothesize</a></span><span class="op">(</span>null <span class="op">=</span> <span class="st">"independence"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/calculate.html">calculate</a></span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"Chisq"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># calculate the null distribution</span></span>
<span><span class="va">null_dist_sim</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="va">candidate_t2</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/specify.html">specify</a></span><span class="op">(</span><span class="va">candidate_t2</span> <span class="op">~</span> <span class="va">education</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/hypothesize.html">hypothesize</a></span><span class="op">(</span>null <span class="op">=</span> <span class="st">"independence"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/generate.html">generate</a></span><span class="op">(</span>reps <span class="op">=</span> <span class="fl">1000</span>, type <span class="op">=</span> <span class="st">"permute"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/calculate.html">calculate</a></span><span class="op">(</span>stat <span class="op">=</span> <span class="st">"Chisq"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Visualize the null distribution and shade the observed statistic</span></span>
<span><span class="va">null_dist_sim</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/visualize.html">visualize</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://infer.tidymodels.org/reference/shade_p_value.html">shade_p_value</a></span><span class="op">(</span><span class="va">observed_indep_statistic</span>,</span>
<span>                direction <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="04_relationships_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section><section id="relationship-between-a-categorical-and-a-continuous-variable-t-test" class="level2" data-number="7.6"><h2 data-number="7.6" class="anchored" data-anchor-id="relationship-between-a-categorical-and-a-continuous-variable-t-test">
<span class="header-section-number">7.6</span> Relationship between a categorical and a continuous variable : t-test</h2>
<p>Thus far, we have examined the relationship between two categorical variables. However, there are instances when we are interested in assessing how various groups vary in terms of their values on a continuous variable. For this, we can use a t-test, which is a statistical test that allows us to compare the means of two groups. The t-test is used to test the null hypothesis that there is no difference between the means of the two groups. The alternative hypothesis is that there is a difference between the means of the two groups. Our goal is to reject the null hypothesis.</p>
<p>Here, I want to know whether men and women tend to have different levels of sympathy towards far right candidates.</p>
<p>H0 : There is no difference between gender in terms of sympathy towards far right candidates.</p>
<p>H1 : There is a difference between gender in terms of sympathy towards far right candidates.</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">symp_zemmour</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   symp_zemmour                                           n
   &lt;dbl+lbl&gt;                                          &lt;int&gt;
 1     0 [Je n'aime pas du tout cette personnalité 0]  1049
 2     1 [1]                                            128
 3     2 [2]                                             95
 4     3 [3]                                             60
 5     4 [4]                                             39
 6     5 [5]                                             62
 7     6 [6]                                             33
 8     7 [7]                                             28
 9     8 [8]                                             15
10     9 [9]                                             11
11    10 [J'aime beaucoup cette personnalité 10]         26
12 NA(a)                                                 29</code></pre>
</div>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">symp_lepen</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   symp_lepen                                             n
   &lt;dbl+lbl&gt;                                          &lt;int&gt;
 1     0 [Je n'aime pas du tout cette personnalité 0]   826
 2     1 [1]                                            155
 3     2 [2]                                            108
 4     3 [3]                                             74
 5     4 [4]                                             45
 6     5 [5]                                            102
 7     6 [6]                                             51
 8     7 [7]                                             50
 9     8 [8]                                             47
10     9 [9]                                             16
11    10 [J'aime beaucoup cette personnalité 10]         83
12 NA(a)                                                 18</code></pre>
</div>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fes2022</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">gender</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  gender        n
  &lt;dbl+lbl&gt; &lt;int&gt;
1 1 [Homme]   747
2 2 [Femme]   828</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Recode gender</span></span>
<span></span>
<span><span class="va">fes2022</span> <span class="op">&lt;-</span> <span class="va">fes2022</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    gender <span class="op">=</span> <span class="fu"><a href="https://larmarange.github.io/labelled/reference/to_factor.html">unlabelled</a></span><span class="op">(</span><span class="va">gender</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">fes2022</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">gender</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  gender     n
  &lt;fct&gt;  &lt;int&gt;
1 Homme    747
2 Femme    828</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Compute the mean</span></span>
<span></span>
<span><span class="va">fes2022</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">gender</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    mean_symp_zemmour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">symp_zemmour</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    mean_symp_lepen <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">symp_lepen</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  gender     n mean_symp_zemmour mean_symp_lepen
  &lt;fct&gt;  &lt;int&gt;             &lt;dbl&gt;           &lt;dbl&gt;
1 Homme    747             1.49             2.14
2 Femme    828             0.916            2.08</code></pre>
</div>
</div>
<p>We can test this statistically by using a t.test that will tell us if the difference in means between the two groups is statistically significant. To do so, we use the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function that takes as input the two variables we want to compare with a <code>~</code> in between and the data where it comes from. Here, we want to compare sympathy towards Marine Le Pen between men and women. So, we put the <code>symp_lepen</code> variable on the left of the <code>~</code> and the <code>gender</code> variable on the right.</p>
<div class="cell">
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_lepen</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">fes2022</span><span class="op">$</span><span class="va">symp_lepen</span> <span class="op">~</span>  <span class="va">fes2022</span><span class="op">$</span><span class="va">gender</span><span class="op">)</span></span>
<span></span>
<span><span class="va">test_lepen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  fes2022$symp_lepen by fes2022$gender
t = 0.39194, df = 1553.9, p-value = 0.6952
alternative hypothesis: true difference in means between group Homme and group Femme is not equal to 0
95 percent confidence interval:
 -0.2421654  0.3631108
sample estimates:
mean in group Homme mean in group Femme 
           2.144011            2.083538 </code></pre>
</div>
</div>
<p>The t-value is our test statistic. It is computed by comparing the difference between the two means to the variability within the groups. The closer the t-value is to 0, the more similar the two groups are. By default, <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> runs a Welch t-test, which does not assume that the two groups have the same variance. Its degrees of freedom are estimated from the data (here 1553.9), which is why they are not a whole number. The formula <code>df = n1 + n2 - 2</code> only applies to the classic Student t-test, which you get with <code>var.equal = TRUE</code>. The p-value is the probability of observing a test statistic as extreme or more extreme than the one we observed if the null hypothesis is true. Based on this critical value and the t-value, the t-table gives us that p-value. Here, the p-value is 0.6952 This means that if there was no difference between the two groups in the population, we would observe a difference at least as large as the one in our sample 69.52% of the time. So we cannot reject the null hypothesis: there is no statistically significant difference between men and women in terms of sympathy towards Marine Le Pen. Note that this does not prove that there is no difference in the population, only that our data do not provide evidence of one.</p>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">test_zemmour</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">fes2022</span><span class="op">$</span><span class="va">symp_zemmour</span> <span class="op">~</span>  <span class="va">fes2022</span><span class="op">$</span><span class="va">gender</span><span class="op">)</span></span>
<span></span>
<span><span class="va">test_zemmour</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  fes2022$symp_zemmour by fes2022$gender
t = 4.8889, df = 1405.6, p-value = 1.13e-06
alternative hypothesis: true difference in means between group Homme and group Femme is not equal to 0
95 percent confidence interval:
 0.3409936 0.7980112
sample estimates:
mean in group Homme mean in group Femme 
          1.4851351           0.9156328 </code></pre>
</div>
</div>
<p>The p-value is 1.13e-06. This means that if there were no difference between the two groups in the population (H0), we would observe a difference at least as large as the one in our sample only 0.000113% of the time. Therefore, we can reject the null hypothesis and conclude that there is a statistically significant difference between the two groups, as the p-value is well below our significance level of 0.05.</p>
<p>While there are no statistically significant differences between women and men in terms of sympathy towards Marine Le Pen, there is a statistically significant difference between women and men regarding sympathy towards Eric Zemmour. Men tend to be more sympathetic towards Eric Zemmour than women.</p>
</section><section id="your-turn" class="level1" data-number="8"><h1 data-number="8">
<span class="header-section-number">8</span> Your turn</h1>
<ul>
<li>Is there a statistically significant difference between gender and the level of other candidates ?</li>
<li>Is there a statistically significant difference between gender and voting choice at the second round ?</li>
</ul>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/malojan\.github\.io\/introduction-r\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../session03/03_dataviz.html" class="pagination-link" aria-label="Data visualization">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data visualization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../session05/correlation_regression.html" class="pagination-link" aria-label="Exploring correlations">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exploring correlations</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/malojan/introduction-r/edit/main/session04/04_relationships.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>